### ISSUE TITLE
Installation instructions

### ISSUE THREAD

**Issue by ttimbers** [jvcasillas/untidydata#2]
@jvcasillas - I would like to use this package in my classroom this fall, and I think my students would benefit from install instructions (i.e., install via `devtools` not `install.packages). Would a pull request to update the docs be welcome?

**Comment by jvcasillas** [comment]
Absolutely 👍🏽

**Comment by jvcasillas** [comment]
Instructions added via https://github.com/jvcasillas/untidydata/pull/3 

Thanks again.
