### ISSUE TITLE
Default url could be the pkgdown site 

### ISSUE THREAD

**Issue by JoFrhwld** [jvcasillas/untidydata#4]
Just creating an issue to explain the minor pull request I'm about to send.

In quarto, links to docs and package sites are automatically inserted if you set the settings:

```
format:
  html:
    code-link: true
```

In text, autolinking to the package page is done with `` `{pkg}` ``, and it defaults to the first url in the description. Putting the pkgdown site as the first url would make for a nicer landing page.

https://github.com/jvcasillas/untidydata/blob/0a0f62741c7f219bd355d20433c9a6e6f6b24818/DESCRIPTION#L13

**Comment by jvcasillas** [comment]
Good catch, @JoFrhwld. Thanks!
